benefitor:
    resource: "@BenefitorBundle/Controller/"
    type:     annotation
    prefix:   /

donor:
    resource: "@DonorBundle/Controller/"
    type:     annotation
    prefix:   /

base:
    resource: "@BaseBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
